CREATE UNIQUE INDEX attr_value_jft_id ON attr_value USING btree (jft_id);
CREATE UNIQUE INDEX fd_id_ad_id_x ON jnt_fic_attr USING btree (fd_id, ad_id);
CREATE INDEX fk_stock_goods_f_id ON stock_goods USING btree (f_id);
CREATE INDEX fk_stock_goods_j_id ON stock_goods USING btree (j_id);
CREATE UNIQUE INDEX idx_case ON format_csv_banque USING btree (upper(name));
CREATE INDEX idx_qs_internal ON quant_sold USING btree (qs_internal);
CREATE UNIQUE INDEX ix_iv_name ON invoice USING btree (upper(iv_name));
CREATE UNIQUE INDEX k_ag_ref ON action_gestion USING btree (ag_ref);
CREATE UNIQUE INDEX ux_po_name ON poste_analytique USING btree (po_name);
CREATE UNIQUE INDEX x_jrn_jr_id ON jrn USING btree (jr_id);
CREATE UNIQUE INDEX x_periode ON parm_periode USING btree (p_start, p_end);
CREATE INDEX x_poste ON jrnx USING btree (j_poste);
