COMMENT ON SCHEMA public IS 'Standard public schema';
COMMENT ON TABLE tmp_pcmn IS 'Plan comptable minimum normalisé';
COMMENT ON TABLE parm_money IS 'Currency conversion';
COMMENT ON TABLE parm_periode IS 'Periode definition';
COMMENT ON TABLE jrn_type IS 'Type of journal (Sell, Buy, Financial...)';
COMMENT ON TABLE jrn_def IS 'Definition of a journal, his properties';
COMMENT ON TABLE jrnx IS 'Journal: content one line for each accountancy writing';
COMMENT ON TABLE form IS 'Forms content';
COMMENT ON TABLE centralized IS 'The centralized journal';
COMMENT ON TABLE "action" IS 'The different privileges';
COMMENT ON TABLE jrn_action IS 'Possible action when we are in journal (menu)';
COMMENT ON TABLE tva_rate IS 'Rate of vat';
COMMENT ON TABLE fiche_def_ref IS 'Family Cards definition';
COMMENT ON TABLE fiche_def IS 'Cards definition';
COMMENT ON TABLE attr_def IS 'The available attributs for the cards';
COMMENT ON TABLE fiche IS 'Cards';
COMMENT ON TABLE jnt_fic_att_value IS 'join between the card and the attribut definition';
COMMENT ON TABLE jnt_fic_attr IS 'join between the family card and the attribut definition';
COMMENT ON TABLE jrn_rapt IS 'Rapprochement between operation';
COMMENT ON TABLE jrn IS 'Journal: content one line for a group of accountancy writing';
COMMENT ON TABLE stock_goods IS 'About the goods';
COMMENT ON TABLE attr_min IS 'The value of  attributs for the cards';
