ALTER INDEX public.action_gestion_pkey OWNER TO phpcompta;
ALTER INDEX public.action_pkey OWNER TO phpcompta;
ALTER INDEX public.attr_def_pkey OWNER TO phpcompta;
ALTER INDEX public.centralized_pkey OWNER TO phpcompta;
ALTER INDEX public.document_modele_pkey OWNER TO phpcompta;
ALTER INDEX public.document_pkey OWNER TO phpcompta;
ALTER INDEX public.document_state_pkey OWNER TO phpcompta;
ALTER INDEX public.document_type_pkey OWNER TO phpcompta;
ALTER INDEX public.fiche_def_pkey OWNER TO phpcompta;
ALTER INDEX public.fiche_def_ref_pkey OWNER TO phpcompta;
ALTER INDEX public.fiche_pkey OWNER TO phpcompta;
ALTER INDEX public.form_pkey OWNER TO phpcompta;
ALTER INDEX public.format_csv_banque_pkey OWNER TO phpcompta;
ALTER INDEX public.formdef_pkey OWNER TO phpcompta;
ALTER INDEX public.invoice_pkey OWNER TO phpcompta;
ALTER INDEX public.jnt_fic_att_value_pkey OWNER TO phpcompta;
ALTER INDEX public.jrn_action_pkey OWNER TO phpcompta;
ALTER INDEX public.jrn_def_jrn_def_name_key OWNER TO phpcompta;
ALTER INDEX public.jrn_def_pkey OWNER TO phpcompta;
ALTER INDEX public.jrn_pkey OWNER TO phpcompta;
ALTER INDEX public.jrn_rapt_pkey OWNER TO phpcompta;
ALTER INDEX public.jrn_type_pkey OWNER TO phpcompta;
ALTER INDEX public.jrnx_pkey OWNER TO phpcompta;
ALTER INDEX public.parameter_pkey OWNER TO phpcompta;
ALTER INDEX public.parm_code_pkey OWNER TO phpcompta;
ALTER INDEX public.parm_money_pkey OWNER TO phpcompta;
ALTER INDEX public.parm_periode_p_start_key OWNER TO phpcompta;
ALTER INDEX public.parm_periode_pkey OWNER TO phpcompta;
ALTER INDEX public.pk_user_local_pref OWNER TO phpcompta;
ALTER INDEX public.qs_id_pk OWNER TO phpcompta;
ALTER INDEX public.stock_goods_pkey OWNER TO phpcompta;
ALTER INDEX public.tmp_pcmn_pkey OWNER TO phpcompta;
ALTER INDEX public.user_sec_act_pkey OWNER TO phpcompta;
ALTER INDEX public.user_sec_jrn_pkey OWNER TO phpcompta;
CREATE UNIQUE INDEX attr_value_jft_id ON attr_value USING btree (jft_id);
ALTER INDEX public.attr_value_jft_id OWNER TO phpcompta;
CREATE INDEX fk_attr_value_jft_id ON attr_value USING btree (jft_id);
ALTER INDEX public.fk_attr_value_jft_id OWNER TO phpcompta;
CREATE INDEX fk_centralized_c_jrn_def ON centralized USING btree (c_jrn_def);
ALTER INDEX public.fk_centralized_c_jrn_def OWNER TO phpcompta;
CREATE INDEX fk_centralized_c_poste ON centralized USING btree (c_poste);
ALTER INDEX public.fk_centralized_c_poste OWNER TO phpcompta;
CREATE INDEX fk_fiche_def_frd_id ON fiche_def USING btree (frd_id);
ALTER INDEX public.fk_fiche_def_frd_id OWNER TO phpcompta;
CREATE INDEX fk_fiche_fd_id ON fiche USING btree (fd_id);
ALTER INDEX public.fk_fiche_fd_id OWNER TO phpcompta;
CREATE INDEX fk_form_fo_fr_id ON form USING btree (fo_fr_id);
ALTER INDEX public.fk_form_fo_fr_id OWNER TO phpcompta;
CREATE INDEX fk_jrn_action_ja_jrn_type ON jrn_action USING btree (ja_jrn_type);
ALTER INDEX public.fk_jrn_action_ja_jrn_type OWNER TO phpcompta;
CREATE INDEX fk_jrn_def ON jrnx USING btree (j_jrn_def);
ALTER INDEX public.fk_jrn_def OWNER TO phpcompta;
CREATE INDEX fk_jrnx_j_poste ON jrnx USING btree (j_poste);
ALTER INDEX public.fk_jrnx_j_poste OWNER TO phpcompta;
CREATE INDEX fk_stock_goods_f_id ON stock_goods USING btree (f_id);
ALTER INDEX public.fk_stock_goods_f_id OWNER TO phpcompta;
CREATE INDEX fk_stock_goods_j_id ON stock_goods USING btree (j_id);
ALTER INDEX public.fk_stock_goods_j_id OWNER TO phpcompta;
CREATE INDEX fk_user_sec_act ON user_sec_act USING btree (ua_act_id);
ALTER INDEX public.fk_user_sec_act OWNER TO phpcompta;
CREATE INDEX fk_user_sec_jrn ON user_sec_jrn USING btree (uj_jrn_id);
ALTER INDEX public.fk_user_sec_jrn OWNER TO phpcompta;
CREATE UNIQUE INDEX idx_case ON format_csv_banque USING btree (upper(name));
ALTER INDEX public.idx_case OWNER TO phpcompta;
CREATE INDEX idx_qs_internal ON quant_sold USING btree (qs_internal);
ALTER INDEX public.idx_qs_internal OWNER TO phpcompta;
CREATE UNIQUE INDEX ix_iv_name ON invoice USING btree (upper(iv_name));
ALTER INDEX public.ix_iv_name OWNER TO phpcompta;
CREATE UNIQUE INDEX k_ag_ref ON action_gestion USING btree (ag_ref);
ALTER INDEX public.k_ag_ref OWNER TO phpcompta;
CREATE UNIQUE INDEX x_act ON "action" USING btree (ac_description);
ALTER INDEX public.x_act OWNER TO phpcompta;
CREATE UNIQUE INDEX x_jrn_jr_id ON jrn USING btree (jr_id);
ALTER INDEX public.x_jrn_jr_id OWNER TO phpcompta;
CREATE INDEX x_poste ON jrnx USING btree (j_poste);
ALTER INDEX public.x_poste OWNER TO phpcompta;
CREATE UNIQUE INDEX x_usr_jrn ON user_sec_jrn USING btree (uj_login, uj_jrn_id);
ALTER INDEX public.x_usr_jrn OWNER TO phpcompta;
